{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "WHOOP API"
  },
  "servers" : [ {
    "url" : "https://api.prod.whoop.com/developer"
  } ],
  "paths" : {
    "/v1/cycle/{cycleId}" : {
      "get" : {
        "tags" : [ "Cycle" ],
        "description" : "Get the cycle for the specified ID",
        "operationId" : "getCycleById",
        "security" : [ {
          "OAuth" : [ "read:cycles" ]
        } ]
      }
    },
    "/v1/cycle" : {
      "get" : {
        "tags" : [ "Cycle" ],
        "description" : "Get all physiological cycles for a user, paginated. Results are sorted by start time in descending order.",
        "operationId" : "getCycleCollection",
        "security" : [ {
          "OAuth" : [ "read:cycles" ]
        } ]
      }
    },
    "/v1/recovery" : {
      "get" : {
        "tags" : [ "Recovery" ],
        "description" : "Get all recoveries for a user, paginated. Results are sorted by start time of the related sleep in descending order.",
        "operationId" : "getRecoveryCollection",
        "security" : [ {
          "OAuth" : [ "read:recovery" ]
        } ]
      }
    },
    "/v1/cycle/{cycleId}/recovery" : {
      "get" : {
        "tags" : [ "Recovery" ],
        "description" : "Get the recovery for a cycle",
        "operationId" : "getRecoveryForCycle",
        "security" : [ {
          "OAuth" : [ "read:recovery" ]
        } ]
      }
    },
    "/v1/activity/sleep/{sleepId}" : {
      "get" : {
        "tags" : [ "Sleep" ],
        "description" : "Get the sleep for the specified ID",
        "operationId" : "getSleepById",
        "security" : [ {
          "OAuth" : [ "read:sleep" ]
        } ]
      }
    },
    "/v1/activity/sleep" : {
      "get" : {
        "tags" : [ "Sleep" ],
        "description" : "Get all sleeps for a user, paginated. Results are sorted by start time in descending order.",
        "operationId" : "getSleepCollection",
        "security" : [ {
          "OAuth" : [ "read:sleep" ]
        } ]
      }
    },
    "/v1/user/measurement/body" : {
      "get" : {
        "tags" : [ "User" ],
        "description" : "Get the user's body measurements",
        "operationId" : "getBodyMeasurement",
        "security" : [ {
          "OAuth" : [ "read:body_measurement" ]
        } ]
      }
    },
    "/v1/user/profile/basic" : {
      "get" : {
        "tags" : [ "User" ],
        "description" : "Get the user's Basic Profile",
        "operationId" : "getProfileBasic",
        "security" : [ {
          "OAuth" : [ "read:profile" ]
        } ]
      }
    },
    "/v1/user/access" : {
      "delete" : {
        "tags" : [ "User" ],
        "description" : "Revoke the access token granted by the user. If the associated OAuth client is configured to receive webhooks, it will no longer receive them for this user.",
        "operationId" : "revokeUserOAuthAccess",
        "security" : [ {
          "OAuth" : [ ]
        } ]
      }
    },
    "/v1/activity/workout/{workoutId}" : {
      "get" : {
        "tags" : [ "Workout" ],
        "description" : "Get the workout for the specified ID",
        "operationId" : "getWorkoutById",
        "security" : [ {
          "OAuth" : [ "read:workout" ]
        } ]
      }
    },
    "/v1/activity/workout" : {
      "get" : {
        "tags" : [ "Workout" ],
        "description" : "Get all workouts for a user, paginated. Results are sorted by start time in descending order.",
        "operationId" : "getWorkoutCollection",
        "security" : [ {
          "OAuth" : [ "read:workout" ]
        } ]
      }
    }
  },
  "components" : {